# .tmux.conf

# 端末側の通常マウス選択・コピーを優先する
set -g mouse off

# TERM は screen-256color より tmux-256color を優先
set -g default-terminal "tmux-256color"

# Esc の反応を少し良くする
set -sg escape-time 10

# copy-mode を vi 風にする
setw -g mode-keys vi

# 履歴は少し増やす
set -g history-limit 100000

# prefix + r で設定再読込
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
